# 2. Modelos de IA

Para o Sent.AI, três modelos de deep learning serão criados, treinados e avaliados - um para classificar se o texto exibe uma recomendação acionável, um para predizer o sentimento geral do texto e outro para identificar a emoção predominante no texto.

**Estrutura**

* Modelo de Recomendação
    * Carregamento dos Dados Preprocessados
    * Desenvolvimento da Arquitetura
    * Train Test Split
    * Treinamento do Modelo
    * Avaliação do Modelo
    * Serialização do Modelo
    
* Modelo de Sentimento Geral
    * Carregamento dos Dados Preprocessados
    * Desenvolvimento da Arquitetura
    * Train Test Split
    * Treinamento do Modelo
    * Avaliação do Modelo
    * Serialização do Modelo
    
* Modelo de Emoção Predominante
    * Carregamento dos Dados Preprocessados
    * Desenvolvimento da Arquitetura
    * Train Test Split
    * Treinamento do Modelo
    * Avaliação do Modelo
    * Serialização do Modelo

## Configurações iniciais

In [2]:
# Importações de libraries importantes

import pandas as pd
import numpy as np
import pickle as pl
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
import tensorflow.keras as keras
import tensorflow as tf

## Modelo de Recomendação

### Carregamento dos Dados Preprocessados

In [4]:
# Carregamento dos dados

recomendacao_texto = pl.load(open("../dados/preprocessados/recomendacao_texto.pkl", "rb"))
recomendacao_label = pl.load(open("../dados/preprocessados/recomendacao_label.pkl", "rb"))

In [5]:
recomendacao_texto

array([[  17, 4125,   28, ...,    0,    0,    0],
       [  53,  420, 1166, ...,    0,    0,    0],
       [  41,  655, 2666, ...,    0,    0,    0],
       ...,
       [ 906,   27,  110, ...,    0,    0,    0],
       [  14, 7056, 6837, ...,    0,    0,    0],
       [  24,  834, 1433, ...,    0,    0,    0]])

In [6]:
recomendacao_label

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [7]:
# One-Hot Encoding da label

recomendacao_label = keras.utils.to_categorical(recomendacao_label, 2)
recomendacao_label

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

### Desenvolvimento da Arquitetura

In [ ]:
class Modelo_de_Recomendacao:
    
    def __init__(self):